In [10]:
#import dependencies/libraries
import pandas as pd
import csv

In [14]:
#declare file
file = "Resources/books.csv"
#read into data frame
# this line gives parse error due to varying row lengths booksDF = pd.read_csv(file)

#work around by putting into list then reread to data frame
#open file, do not forget encoding!
f_work = open(file, 'rt', encoding = 'utf-8')
#read it in
reader = csv.reader(f_work)
#put into a list
csv_list = []
for item in reader:
    csv_list.append(item)
#close file
f_work.close()
#read into data frame
booksDF = pd.DataFrame(csv_list)
booksDF.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,None
1,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.,None
2,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.,None
3,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic,None
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.,None